# Generated by Django 3.2.5 on 2021-08-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_alter_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
