# Generated by Django 3.2.5 on 2021-08-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0007_remove_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Draft'), ('p', 'Published')], max_length=1, null=True),
        ),
    ]
