# Generated by Django 3.2.5 on 2021-08-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0011_alter_book_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
