# Generated by Django 3.2.5 on 2021-08-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0013_auto_20210821_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
