# Generated by Django 3.2.5 on 2021-08-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0014_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amount',
            field=models.IntegerField(default=False),
        ),
    ]
