# Generated by Django 3.2.5 on 2021-08-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0015_book_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='released_year',
            field=models.DateTimeField(),
        ),
    ]
