# Generated by Django 3.2.5 on 2021-10-13 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0016_alter_book_released_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='released_year',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
